services:
  superpets:
    image: ${DOCKER_REGISTRY-}superpets
    build:
        context: .
        dockerfile: Dockerfile
    ports:
     - "8081:80"
    depends_on:
     - sqldata    

  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
     - SA_PASSWORD:SuperPets@)@#2023
     - ACCEPT_EULA=Y
    ports:
     - "1450:1433"