services:
  superpets:
    image: ${DOCKER_REGISTRY-}superpets
    build:
        context: .
        dockerfile: Dockerfile
    ports:
     - "8081:80"
    depends_on:
     - sqldata    

  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SuperPets2023
    ports:
     - "1450:1433"